import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavBar } from './_components/navbar'
import { Footer } from './_components/footer'
import { QForm } from './_components/query-form'
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <QForm />
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
